### ISSUE TITLE
Sync cmd: 1/10 num prefix

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#101]
The num prefix is constantly equal to 1/10.

```$ dvc sync data/
(1/10): [####################################### ] 99% model.p_51b6e1a
```

**Comment by efiop** [comment]
Could you share steps to reproduce?

**Comment by dmpetrov** [comment]
It happens to me all the time when I sync something to cloud.
I went through the tutorial (~10 files in `.cache`) and `dvc sync data`. It syncs correctly but I constantly see 1/10 as a progress.

**Comment by efiop** [comment]
Thanks, I'll take a look shortly.
