### ISSUE TITLE
Is there any way to store data on private cloud?

### ISSUE THREAD

**Issue by gabrielelanaro** [dataversioncontrol/dvc#116]
Hi, I saw dvc current storage options are s3 and aws. Can other storages be easily supported? 

For example an s3-compatible api such as https://minio.io/, or straight-on rsync?

**Comment by dmpetrov** [comment]
Hi @gabrielelanaro . It is relatively easy to add a new storage but some coding is required - look at `DataCloudBase` class and `DataCloudAWS`. Please feel free to submit a pull request with code.

`rsync` - you can just sync the entire repository.

**Comment by gabrielelanaro** [comment]
I checked out the code and look pretty straigthforward, thanks!

**Comment by efiop** [comment]
Hi @Instantnoodles-madman Please see `dvc/fs/s3.py`

**Comment by shcheklein** [comment]
@Instantnoodles-madman and may be add a bit to this. If you'd like to use minio or any other private/public S3-compatible cloud, you don't need to change anything. All you need is to setup `endpointurl` as described in the `Click for S3 API compatible storage` here -  https://dvc.org/doc/command-reference/remote/modify
