### ISSUE TITLE
No module named model_selection error in python 2.7

### ISSUE THREAD

**Issue by vishwanath79** [dataversioncontrol/dvc#119]
While splitting the training and testing dataset to two output files. Encountering a import error.

```
DVC $ dvc run python code/split_train_test.py data/Posts.tsv 0.33 20170426 data/Posts-train.tsv data/Posts-test.tsv
Git command error (python code/split_train_test.py data/Posts.tsv 0.33 20170426 data/Posts-train.tsv data/Posts-test.tsv):
Traceback (most recent call last):
  File "code/split_train_test.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ImportError: No module named model_selection
```
Further research indicated this is due to older scikit versions calling this  module "train_test_split" now been renamed to model_selection.

`pip install -U scikit-learn`

solved the issue. 

Suggest instructions can be added to the README if deemed useful? Thanks.

**Comment by dmpetrov** [comment]
@vishwanath79 thank you! Good catch.

I'm adding the updating option to `pip install -U -r code/requirements.txt`. It fixes the issue. The same change in the tutorial: https://blog.dataversioncontrol.com/data-version-control-beta-release-iterative-machine-learning-a7faf7c8be67

**Comment by vishwanath79** [comment]
Thank you @dmpetrov

**Comment by Rootmannii** [comment]
This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
  And for requirements I keep getting;
Could not open requirements file: [Errno 2] No such file or directory: 'code/requirements.txt'

**Comment by shcheklein** [comment]
@Rootmannii hi, could you share the exact commands you are running? And the link to the tutorial you try to reproduce, please. Thank you!
