### ISSUE TITLE
Auto dependency calculation --auto-dag

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#130]
Currently DVC implicitly derives dependencies based on command line args. 
```$ dvc run python mycode.py data/input.csv data/output.p```
It goes like this:
1. If arg (let say `data/output.p`) looks like data file (in `data` dir) we assume it is an input parameter.
2. If a data file was changed we change our mind and say the arg is an output.

Also, we have a special args like `--input` or `-i` and `--output` or `-o` for explicit input\output definition.

**Should we keep auto\implicit dependency calculation or we should hide this logic behind, let say `--auto-dag` or `-a` option?**

Result will be:
```$ dvc run --auto-dag python mycode.py data/input.csv data/output.p```
or explicitly:
```$ dvc run -i data/input.csv -o data/output.p python mycode.py data/input.csv data/output.p```

**Comment by dmpetrov** [comment]
Actually, we use two step dependency calculation:
1. Command line based.
2. Repository state based (before and after command run).

Both of them make DVC logic quite fragile.

To make DVC more persistent we should probably turn off both of the options by default. New parameters `--auto-args`, `--auto-git` or combined `--auto-dag` will include one of these.

And best practice should be - specify your inputs and outputs explicitly.

**Comment by dmpetrov** [comment]
One more specific case https://github.com/dataversioncontrol/dvc/issues/154

**Comment by efiop** [comment]
Add --no-auto-dag as a temporary solution.

**Comment by efiop** [comment]
No longer relevant, as we switched to explicit dependencies.
