### ISSUE TITLE
Package auto building - Linux

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#134]
Where to get the package files?

**Comment by efiop** [comment]
From now on, deb and rpm packages are automatically built and deployed to github releases by travis. To obtain linux pkgs, you will need to simply create a dvc release and wait ~10 minutes while travis will build and upload dvc.{rpm, deb} for you.  I.e. see test release https://github.com/dataversioncontrol/dvc/releases/tag/0.8.7.4-appveyor-release-test .
