### ISSUE TITLE
Package auto building - Windows

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#135]
Where to get the installer file?

**Comment by efiop** [comment]
From now on, windows installer is automatically built and deployed to github releases by appveyour. To obtain a windows installer, you will need to simply create a dvc release and wait ~10 minutes wile appveyor will build and upload dvc.exe for you.  I.e. see test release https://github.com/dataversioncontrol/dvc/releases/tag/0.8.7.4-appveyor-release-test .
