### ISSUE TITLE
allow multiple "root"

### ISSUE THREAD

**Issue by ophiry** [dataversioncontrol/dvc#169]
currently it's possible to have a single dvc.conf in the repository root
having a dvc.conf in other places will allow:
1. don't "pollute" the repository root (which may be an issue in large multi project repos)
2. allow to have multiple dvc "instances" in the repo (also useful for large projects)

the "active" dvc.conf could be selected by an environment variable or a command line option

**Comment by efiop** [comment]
I'm not sure why one would need to have a few dvc configs for the same project. Different clouds? Different data dirs?

I'm not sure I follow, could you provide an example or two please?

**Comment by ophiry** [comment]
two data dirs - for two projects in the same repo

**Comment by dmpetrov** [comment]
@ophiry It looks like this issue was resolved by the new design with data files in any directory, not only in `data`.
Could you please confirm that or disagree with that?

**Comment by ophiry** [comment]
indeed

**Comment by dmpetrov** [comment]
Thank you!
Closing...
