### ISSUE TITLE
A single commit for multiple runs

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#185]
If `dvc repro` generates a few run commands each of these will be as a single commit. 
```
$ git log
DVC run: python code/evaluate.py data/model.p data/matrix-test.p data/evaluation.txt
...
DVC run: python code/train_model.py data/matrix-train.p 20170426 data/model.p
```

Is it possible to make all the runs and then make a single commit:
```
$ git log
DVC repro: code/evaluate.py
```

**Comment by dmpetrov** [comment]
Biggest concern - each run-command can change the environment in a way dvc won't recognize. So, separate commits are safer.

**Comment by dmpetrov** [comment]
One more thought - it looks like repro changes are more important than others from workflow visualization point of view, so these changes cannot be collapsed into a combined commit. However, repro changes can be a final step in a combined commit.

**Comment by efiop** [comment]
No longer relevant with the new design, as we now don't commit anything for user except for 'dvc init'.
