### ISSUE TITLE
Add LogLevel param in command line (easy)

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#19]
We need two types of logs:
1) console output (by default: info and above)
2) log output (by default: debug and above)

Both of the values have to be presented in the dvc.conf file. Like 
```
ConsoleLogLevel = Info
LogLevel = Debug
LogFile = dvc.log # what about system log do we need that?
```

The config log parameter ConsoleLogLevel could be override by command line:
`dvc run --verbose debug Rscript plotting.R data/input.csv`.

PS: do not forget Windows support.

**Comment by efiop** [comment]
After a discussion with @dmpetrov , it was decided to instead add quick cmdline switches for verbosity. I.e. -q|--quiet and -v|--verbose, as these are the ones that are actually used by cmdline users. Here is a pull request that adds -q and -v options and does other things to improve logging. https://github.com/dataversioncontrol/dvc/pull/80

**Comment by efiop** [comment]
#80
