### ISSUE TITLE
Use posixpath everywhere

### ISSUE THREAD

**Issue by efiop** [dataversioncontrol/dvc#198]
This is related to #78 . It was temporarily fixed by converting state files to unix format, but in general, we should make dvc work with posixpath exclusively, similar to how git works.

**Comment by efiop** [comment]
Leaving for consideration for the next release.

**Comment by villasv** [comment]
Using `pathlib` from python 3 would solve the issue, are you guys requiring python 2 support?

**Comment by efiop** [comment]
We do aim at supporting both python 2 and 3 at the same time. We do know about pathlib and even used it for quite some time, but we didn't find it to be a good fit within the project and thus removed it for now. I would totally consider the possibility of using it in the future, though, just not it this release.

**Comment by efiop** [comment]
Seems to be easier to work with whatever paths we've got and convert where needed as we do right now. Closing.
