### ISSUE TITLE
move dvc.conf, .state, .cache to .dvc/{config, state, cache}

### ISSUE THREAD

**Issue by efiop** [dataversioncontrol/dvc#200]

**Comment by ophiry** [comment]
Got does it affect existing repos? Do they need to be converted manually?

**Comment by efiop** [comment]
@ophiry it actually does =( But this is something we better do earlier than later. I planned to introduce a "converter" script to migrate old repos to new versions to avoid carrying overhead. Would something like that suit you?

**Comment by ophiry** [comment]
Yes

**Comment by ophiry** [comment]
@efiop  is there a list of things that need to be changed to do the repo migration?

**Comment by efiop** [comment]
@ophiry As of right now, you'll need to move config to .dvc/config, .state to .dvc/state and .cache to .dvc/cache. That should be it. Notice that there are other changes coming for state files format too.

**Comment by ophiry** [comment]
I assume the links should also be recreated - don't they?

anything else?

**Comment by efiop** [comment]
Correct, they do need to be changed appropriately.
You will also have to rename cache files to have full sha and not short one like they used to have =(. There are even more backward-incompatible changes coming. Next release will probably the one where we will stabilize it =(.

**Comment by efiop** [comment]
@ophiry Hi! It's been a long time, but we finally released new version today :) If I recall correctly, you were using some intermediate dvc version from git repo, thus I don't think 'converter script' would be a viable option. That being said, I would be extremely happy to assist you in migrating your repos to v0.9. We stabilized repository format and from now on guarantee 100% backward compatibility.

**Comment by ophiry** [comment]
Thanks! I'll try out the new version
