### ISSUE TITLE
error when pulling in a new git clone 

### ISSUE THREAD

**Issue by ophiry** [dataversioncontrol/dvc#201]
after performing a git clone of a dvc enabled repository

`dvc pull data/
`
`Unexpected exception while processing targets: [Errno 2] No such file or directory: '.cache/1.csv_e202149'
`

**Comment by efiop** [comment]
Thank you for the feedback!

I reproduced, fixed and added a test for this issue in #202.
Feel free to reopen if it didn't solve it for you.

Cheers!
