### ISSUE TITLE
Is dvc init target needed?

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#208]
Do we really need target file in dvc init?

```
$ dvc init -h
usage: dvc init [-h] [-q] [-v] [-G] [--data-dir DATA_DIR]
                [--cache-dir CACHE_DIR] [--state-dir STATE_DIR]
                [--target-file TARGET_FILE]
```

**Comment by efiop** [comment]
I actually removed it from init in https://github.com/dataversioncontrol/dvc/pull/207 .
Target file, state dir and cache dir don't have to be configurable. We're safe by simply using .dvc/{target, state, cache}.

It might be even worth it to remove target file totally and use an entry in config file for that. Unless I'm missing some scenarios.

**Comment by efiop** [comment]
I.e. after #207, dvc init -h looks like:
`(dvc) ➜  dvc git:(master) ✗ dvc init -h                                     
usage: dvc init [-h] [-q] [-v] [-G] [--data-dir DATA_DIR]                   
                                                                            
optional arguments:                                                         
  -h, --help            show this help message and exit                     
  -q, --quiet           Be quiet.                                           
  -v, --verbose         Be verbose.                                         
  -G, --no-git-actions  Skip all git actions including reproducibility check
                        and commits.                                        
  --data-dir DATA_DIR   Data directory.                                     
`
