### ISSUE TITLE
Use full commit id

### ISSUE THREAD

**Issue by efiop** [dataversioncontrol/dvc#229]
Currently we use short versions of commit id for our state files, but we should really use full sha, as current approach might cause problems in bigger projects where short sha will be ambiguous.

**Comment by dmpetrov** [comment]
We can keep it as an configurable option. With 7 by default.

Actually we already have this option in Config class. We just need to extract it into config file.

**Comment by efiop** [comment]
Why should it be configurable at all?

**Comment by dmpetrov** [comment]
Full sha does not look good. This is actually the only concern that I have.

**Comment by efiop** [comment]
I don't think that should be a problem, as it is not like people are not used to seeing full shas and cache files are not for the public eye anyway =). The problem I'm afraid of is that we might run into ambiguity later, as bigger projects will have a bigger chance of having partially matching shas, when older one will be 12345 and newer will be 123456. And I think we should move to full shas while we still can and forget about even potential issues for good.

**Comment by dmpetrov** [comment]
Yes, let's move to full hashes. Otherwise short hashes will hurt us one day...
