### ISSUE TITLE
can't use aws buckets with periods in the name

### ISSUE THREAD

**Issue by earlh** [dataversioncontrol/dvc#23]
see discussion here:
https://github.com/boto/boto/issues/2836

eg boto won't work with bucket 'a.b' but will with 'a-b'; requesting a key for any bucket with a period in the name returns None

**Comment by dmpetrov** [comment]
Common case :( People likes to use their domain name as a bucket.

**Comment by earlh** [comment]
Yeah, guess how I found it :D :D. Two hours ending with "I'm copying and pasting the goddamn code sample exactly as written".

Unfortunately, there doesn't seem to be an easy solution; the most direct one is editing `~/.boto` but that doesn't necessarily work.  Worse yet, `~/.boto` is *also* used by gc/`gsutils`, and I'm not sure if the change is compatible with both.  That's at bare minimum a pain for dev.

**Comment by efiop** [comment]
Fixed with #651 by migrating to boto3, which has that bug fixed.
