### ISSUE TITLE
state-dir and cache-dir options should be removed from the command-line interface of DVC

### ISSUE THREAD

**Issue by gvyshnya** [dataversioncontrol/dvc#238]
I noticed the output of _dvc init –h_ contains lines,
- [--cache-dir CACHE_DIR] [--state-dir STATE_DIR]

Expected behavior:
- Given the fact of recent move of cache and state dirs into the static .dvc folder, those options should no more be available in the commands when you call **dvc init**
- the output of **dvc init -h** should not contain the information on --cache-dir and --state-dir 

**Note**: this is reproducible on dvc v. 0.8.7

**Comment by efiop** [comment]
They are long gone in master.
```
(dvc) ➜  functest git:(master) ✗ dvc init -h
usage: dvc init [-h] [-q] [-v] [-G] [--data-dir DATA_DIR]

optional arguments:
  -h, --help            show this help message and exit
  -q, --quiet           Be quiet.
  -v, --verbose         Be verbose.
  -G, --no-git-actions  Skip all git actions including reproducibility check
                        and commits.
  --data-dir DATA_DIR   Data directory.
```

Feel free to reopen if i missed something.
