### ISSUE TITLE
Weird Exception on illegal argument/option provided in DVC command line

### ISSUE THREAD

**Issue by gvyshnya** [dataversioncontrol/dvc#239]
**Summary:** A weird user-unfriendly exception displayed when a user attempts to execute dvc with illegal/not supported arguments/options in the command line

**Steps to reproduce:**
- open your command line shell
- type **dvc -v** in the command line (this is the illegal command, unlike _dvc -V_)

**Expected behavior:**
- a graceful user-friendly error message displayed (something like, "Illegal option or command line argument: -v")

**Actual behavior:**
- the low-level user-unfriendly exception displayed below as follows:

`Exception caught while parsing settings
Traceback (most recent call last):
  File "c:\python\python36\lib\site-packages\dvc\main.py", line 11, in main
    settings = Settings(sys.argv[1:])
  File "c:\python\python36\lib\site-packages\dvc\settings.py", line 29, in __ini
t__
    config = Config()
  File "c:\python\python36\lib\site-packages\dvc\config.py", line 75, in __init_
_
    raise ConfigError('Config file "{}" does not exist {}'.format(conf_file, os.
getcwd()))
dvc.config.ConfigError: Config file error: Config file "dvc.conf" does not exist`

**Comment by efiop** [comment]
Very interesting. This is actually a bug in python3's argparser. In python2, execution doesn't even come to that line, as argparser catches that there is no cmd specified:
```
(dvc) ➜  functest git:(master) ✗ dvc -v                                               
usage: dvc [-h] [-q] [-v] [-G] [-V]                                                   
           {init,run,sync,pull,push,status,repro,remove,import,lock,gc,ex,config,show}
           ...                                                                        
dvc: error: too few arguments                                                         
```
Will introduce workaround for Python3 shortly.

Thanks for the feedback!
