### ISSUE TITLE
dvc.conf not created automatically when you install dvc via Python pip package on Windows

### ISSUE THREAD

**Issue by gvyshnya** [dataversioncontrol/dvc#240]
This has been observed for dvc 0.8.7

**Comment by efiop** [comment]
hi! Could you please elaborate?

**Comment by gvyshnya** [comment]
Sorry for possible confusion. If this is not the actual problem, please feel free to simply close it.

The reason I opened this issue at the first place was the fact I could not find *dvc.conf* on my local file system (my machine runs Windows 7, 64 bit and Python 3.6).

I tried to look it up in the following ways

- run the global file search, using Window File Search tool (available in the start menu) - it returned nothing
- do the physical visual inspection of the folder where dvc.exe app deployed (in my case, it is *C:\Python\Python36\Scripts*)
- do the physical inspection of the folder where dvc package deployed within the python environment (in my case, it is *C:\Python\Python36\Lib\site-packages\dvc*)
