### ISSUE TITLE
'dvc run' overrides existing data cache

### ISSUE THREAD

**Issue by efiop** [dataversioncontrol/dvc#278]
I.e. lets say data/file exists. If one was to run 'dvc run cp otherfile data/file', dvc would override data/file(and its cache) causing cache corruption. There seems to be no good way to automagically detect this without copying cache somewhere safe. I have a few thoughts on how to workaround this. Will prepare test patch soon.

**Comment by dmpetrov** [comment]
Have you considered read-only mode? https://github.com/dataversioncontrol/dvc/issues/276

**Comment by efiop** [comment]
You are right, #276 will be a nice workaround for this issue. Already preparing a patch.
