### ISSUE TITLE
better error message when you're screwed

### ISSUE THREAD

**Issue by earlh** [dataversioncontrol/dvc#28]
ie you get yourself in the state where you have file `data/X` where `X` doesn't exist  in `cache` or cloud

**Comment by earlh** [comment]
in current batch of config fixes

**Comment by dmpetrov** [comment]
To me, it looks like you can have no cache for a data file. You just need to repro the file.

**Comment by earlh** [comment]
I still think a message along the lines of "X is not in local cache or in remote storage" is an improvement
