### ISSUE TITLE
Don't use big data files in functional tests without need

### ISSUE THREAD

**Issue by efiop** [dataversioncontrol/dvc#283]
A bunch of our tests use giant data files from aws, which requires too much time to complete downloading/uploading. Rework our tests to use small data files where possible and only use big data where there is real need for it.

**Comment by dmpetrov** [comment]
There is a real need in the tutorial scenarios. With smaller datasets the model diverges and the target metric behaves like a random number generator. Even 25K dataset has this issue partially.

Smaller data sets can be used for all other func tests.

Sent from my iPhone

**Comment by efiop** [comment]
@dmpetrov Sure, tutorial scenarios will surely stay with current big data files. I'm talking more about other func tests, where some basic functionality is tested and they don;t depend on data content at all.
