### ISSUE TITLE
DVC Utils

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#308]
Do we need to create `dvc utils` to cover common scenarios for Unix and Windows:

```
$ dvc utils seq 1 10 0.1 # unix seq
$ dvc utils seq 1 10 0.1 --exp # extended unix seq
$ dvc utils import https://... # unix wget 
....
```

**Comment by efiop** [comment]
I don't think we should bother with it, as there are plenty of existing solutions and it is not worth it for us to bear the burden of maintaining it.
