### ISSUE TITLE
dvc show workflow: target metric change is not reflected in a graph

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#316]
A metric was changed from 0.59 to 0.60 as result of algo params change and `dvc repro`. However, the change was not reflected in the graph.

I assume this is a result of the last design change.

![workflow](https://user-images.githubusercontent.com/10081867/33252079-9af8f894-d2f0-11e7-96a4-52dba8a2253e.jpeg)

**Comment by efiop** [comment]
Not relevant anymore. Closing.
