### ISSUE TITLE
Add merge strategy names

### ISSUE THREAD

**Issue by efiop** [dataversioncontrol/dvc#323]
It simply would be nicer to have some infrastructure in place for possible additional merge helpers in the future.

**Comment by dmpetrov** [comment]
Right. But now we have only one not a standard strategy for merging - branches with different data sources. All other strategies can be easily implemented by Git itself.

```
# the specified sources should stay in original branches
$ dvc merge keep-source file.tgz locations.tgz 

# All sources should stay in original branches
$ dvc merge keep-source --all
```

**Comment by dmpetrov** [comment]
We decided to remove `dvc merge` - with the new design regular `git merge` should work fine.
