### ISSUE TITLE
Any ideas how to use it on multiple instances?

### ISSUE THREAD

**Issue by olegserov** [dataversioncontrol/dvc#345]
I'm sorry, but I'm a little bit confused here. Image I have a huge batch that needs processing. I want to process it on multiple server instances. How can I ensure that the data will be assigned  proper version?

**Comment by dmpetrov** [comment]
Hi @olegserov,
A few questions to clarify your scenario:
1. Should all the files from the batch be processed the same way in (theoretically) parallel? 
2. What are you going to do with the outputs? Choose only the best output or combine\assemble all the outputs?
3. Would you like to create all the outputs in a new branch or the same (master) branch is fine?

**Comment by olegserov** [comment]
Dmitry, thanks for the quick response. 
1. Yes, I was thinking about feature extraction on thousands of input files. It can be easily sped up by processing it on multiple instances/cpus.
2. I am thinking about collecting them into one batch-revision-checkpoint (I don't know the right terminology in the project's context). I am not talking about a map-reduce (when the individual outputs are disregarded and only merged output is saved).
3. I don't see any restrictions here...

**Comment by dmpetrov** [comment]
Performing computation in the cloud is not implemented in the current DVC version. So, you need to run cloud machines and clone the git repository to the machines manually.

Then you just run computations on separate machines file by file, dvc commits the changes. After all the computations are done - don't forget to push your changes to a correct (master) branch of the repository and don't forget to sync data to a cloud storage `dvc sync` on each machine.

If everything is done correctly you will have your repository with all the changes and all the files in your cloud storage. `git pull && dvc sync` will update all the data into your machine.

All the version will be correctly assigned. Versions through Git repository and data/content through cloud storage.

**Comment by olegserov** [comment]
Thank you!

**Comment by efiop** [comment]
Seems to be resolved. Closing for now. Feel free to reopen if needed.
