### ISSUE TITLE
How stable is the versioning?

### ISSUE THREAD

**Issue by villasv** [dataversioncontrol/dvc#346]
I've noticed big interface and interop changes between version 0.8.6 from pip and the current master branch (lastly pre-released as 0.8.8).

How far are we from a 1.0.0 release candidate, from which point we would have strict backward compatibility according to semantic versioning?

**Comment by efiop** [comment]
Hi @villasv !

Thank you for your question! We're working on some major changes in master in order to stabilize the project for the next release(will probably be called 0.9.0 and should be released until mid-January), from which point on we should have strict backward compatibility.

**Comment by villasv** [comment]
Great news :)
