### ISSUE TITLE
Add files directly from S3 without https

### ISSUE THREAD

**Issue by villasv** [dataversioncontrol/dvc#349]
Following the example where we could add a file directly from a https:// resource, it would be nice to be able to do the same with private cloud files like s3://, using the supposedly already present AWS credentials or just trusting boto3 default credential handling.

**Comment by dmpetrov** [comment]
In the new DVC version, we decided to get rid of `dvc import` which does HTTP request. Motivation - it is not DVC job to upload files, DVC only tracks files and communicates to cloud storages but not to external storages.

The code might look like:
```
$ aws s3 cp s3://mybucket/dir1/file1.tsv .
$ dvc add file1.tsv # Convert the file to a data file (content won't be pushed into Git)
$ git commit -m 'Import file1'
# S3\GCP storage synchronization works like it used to be (only command was renamed):
$ dvc push file1.tsv
```

The same way you can add a directory:
```
$ aws s3 cp --recursive s3://mybucket/dir1/dir2 .
$ dvc add dir2 # Convert all the files from a directory to data files
$ git commit -m 'Import dir2'
```

Does it solve the issue?

**Comment by villasv** [comment]
So if I understand it correctly, `add` also behaves differently in the sense that it will also move the data file to the cache and replace the original with the link? Because with `import` I'd only import files from outside the project directory because it would commit the original it as well. This difference makes sense with the renaming.

If that's the case, then the first snipped is indeed all that's needed.

**Comment by dmpetrov** [comment]
Yes, your understanding is correct.

Cool. I'm glad it works for you.
