### ISSUE TITLE
Use bash on windows for functional tests(i.e. with cram)

### ISSUE THREAD

**Issue by efiop** [dataversioncontrol/dvc#350]
Windows 10 actually comes with bash(c:\shell.w32\bash.exe) and we can use it to unify our func tests for both win and *nix.

**Comment by villasv** [comment]
AFAIK you need to enable the Linux Subsystem as a Windows Feature, so bash not available by default.
It's trivial to install it, though.

**Comment by efiop** [comment]
@villasv thanks for the heads up! Luckily we don't really need this anymore, as with the recent internals redesign unittests will take most of the testing. Closing.
