### ISSUE TITLE
enum34 package is not compatible with Python >= 3.6.1

### ISSUE THREAD

**Issue by villasv** [dataversioncontrol/dvc#357]
Currently making the `build_windows.cmd` command fail.
This requirement should be replaced with `enum-compat`, which will correctly no-op for Python > 3.4.

Not sure where is this requirement coming from, because installing `master` from pip works fine.

**Comment by dmpetrov** [comment]
@villasv thank you for reporting! This will be fixed once we stabilize the current codebase for *nix platforms.

The current `master` branch is not stable due to the development of the new version. The last stable version is 0.8.5.
