### ISSUE TITLE
PyInstaller==3.2.1 is incompatible with Python >= 3.6

### ISSUE THREAD

**Issue by villasv** [dataversioncontrol/dvc#358]
IIRC it started being compatible after version 3.3
Currently running `build_windows.cmd` with Python 3.6.3 will yield:

```
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  ...
  File "c:\python36\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range
```

**Comment by dmpetrov** [comment]
This is related to #357 - the current code in `master` branch is under active development.

**Comment by efiop** [comment]
This is pyinstaller's bug. We are building our binary packages on 2.7 and with 'python' packages you don't have to use pyinstaller at all. Closing.
