### ISSUE TITLE
Check why travis doesn't update codeclimate score

### ISSUE THREAD

**Issue by efiop** [dataversioncontrol/dvc#368]

**Comment by efiop** [comment]
Fixed by #373

**Comment by efiop** [comment]
Hm, it says that it uploads report successfully but I can't see the score changing at https://codeclimate.com/github/dataversioncontrol/dvc . Need to investigate more.

**Comment by dmpetrov** [comment]
It can take a few minutes to update. Or just a bug.

**Comment by efiop** [comment]
I suspect that too, but it has been almost 2h and that's why I started to worry and reopened this issue. Will check back in the morning.

**Comment by efiop** [comment]
Hm... Still nothing. Had to update the score manually.

**Comment by efiop** [comment]
Couldn't figure out what was wrong. Used codecov instead, everything(including combining reports from appveyor and travis) worked from the first try.
