### ISSUE TITLE
Add --no-run option to dvc run

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#385]
A better option name can be proposed.

**Comment by villasv** [comment]
Is the goal of this option to just register the dependency but not actually run the command?  `--no-run` is an option kinda weird for the `run` command. I'd suggest `--no-exec` to keep a similar structure.

Or the option could mean the opposite of eager execution:  `--not-now` if humor is allowed and `--postpone` if not, or something along these lines.

**Comment by dmpetrov** [comment]
I like yours `--no-exec`. I've created the issues while I was talking with @efiop by Skype - didn't have time to think of a good name :)

Use case:

```
$ dvc run --no-exec -d code/train_model.py -d data/matrix-train.p -o data/model.p python code/train_model.py data/matrix-train.p 20170426 data/model.p
$ dvc run --no-exec -d code/evaluate.py -d data/model.p -d data/matrix-test.p -O data/eval_auc.txt python code/evaluate.py data/model.p data/matrix-test.p data/eval_auc.txt
$ dvc run --no-exec -d data/eval_auc.txt  # Create the major Dvcfile with PHONY goal  
```

Nothing was actually run. Now you run all in once (probably in a different machine):
```
$ dvc repro
```

**Comment by efiop** [comment]
I actually jokingly said '--no-run' during the conversation with the intent to find a better name later :) . I also really like '--no-exec' so I'll use it in an upcoming patch. Thanks!
