### ISSUE TITLE
Unit test for state files

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#397]
It looks like we have some issues with state file.

This might be a part of `test_fsck.py`

One more idea - extract state file checking logic in a separate file\class. Like - for a given file `mtime`, state file and dependency files. This logic is partially implemented in `fsck.FsckFile` class. This code should be reused in `fsck` as well as `repro`.

**Comment by efiop** [comment]
What kind of issues? Could you share more details?

**Comment by dmpetrov** [comment]
Created the bug for myself mostly.
I saw a strange behavior when I was playing with `fsck`. It might be just `fsck` issue. This is how I got the idea to unify the code.

**Comment by efiop** [comment]
Oh, I see.

**Comment by efiop** [comment]
No longer relevant. Closing.
