### ISSUE TITLE
Do not check cloud credentials

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#40]
dvc should work out of box without any cloud credentials and error\warning messages.

Currently:
```
$ dvc run python code/df_to_matrix.py data/Posts-bin-fr-test.tsv data/Posts-test-matrix.p
Error. config 'dvc.conf' is not correctly setup.  Please fix:
Error.     can't find aws credentials.  TODO
```

Desired behavior:
- by default, no cloud is set in config "Cloud = ". No checking.
- if Cloud is set in config - dvc complains only in cloud related commands (sync currently and remove)

**Comment by earlh** [comment]
done; will push as part of another batch of config stuff
