### ISSUE TITLE
Running DVC outside of Git dir

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#416]
We should handle all the cases like this.

```
cd /
$ dvc repro
No handlers could be found for logger "dvc"
```

**Comment by efiop** [comment]
Looks you are using an older version.

(python3-dvc) ➜  ~ cd /
(python3-dvc) ➜  / dvc repro
Initialization error: Not a dvc repository (or any parent up to mount point /)

Please update your repo.

**Comment by efiop** [comment]
Oops, this is accidental degradation. Not long ago it said:
(python3-dvc) ➜  ~ cd /
(python3-dvc) ➜  / dvc repro
Initialization error: Not a dvc repository (or any parent up to mount point /)

Will fix soon and cover by a test.
