### ISSUE TITLE
dvc show: command line options

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#424]
1. Do not generate dot files
`pipeline_all.dot` and `workflow.dot` should be generated only with a special option like '-D'

2. Output filename option is needed like `dvc shod pipeline -o graph.jpeg`

3. Rename `pipeline_all.jpeg` to `pipeline.jpeg`

**Comment by dmpetrov** [comment]
Update: `dvc show pipeline` has 'target' param (data directory). It looks like the param is not relevant anymore and has to be removed.

**Comment by dmpetrov** [comment]
`workflow` is not relevant anymore but `pipeline` still is...

**Comment by efiop** [comment]
Pipeline was removed as well. Closing.
