### ISSUE TITLE
working behind corporate proxy

### ISSUE THREAD

**Issue by tc-ying** [dataversioncontrol/dvc#441]
is there an option for dvc to connect internet behind proxy? like `dvc import --proxy`?

**Comment by dmpetrov** [comment]
Hi @tc-ying 
Thank you for your using DVC!
`dvc import` is going to be deprecated in the new DVC version since we are removing not core features out of the tool.

In the new version it will work this way:
```
$ export http_proxy=http://myproxy.mycorp.com:9999/
$ wget http://example.com/file.txt -O example_sources/file.txt
$ dvc add example_sources/file.txt
```

**Comment by tc-ying** [comment]
i suppose `dvc sync` with cloud sources is to be deprecated likewise?

if so i'm done, thanks !!

**Comment by dmpetrov** [comment]
@tc-ying
No, `dvc sync` works. Now it is called `dvc push` and `dvc pull`. This is how you suppose to transfer data.

```
$ export HTTP_PROXY=http://myproxy.mycorp.com:9999/
$ export HTTPS_PROXY=http://myproxy.mycorp.com:9998/
$ wget http://example.com/file.txt -O example_sources/file.txt
$ dvc add example_sources/file.txt
$ dvc push
```

On a client side:
```
$ export HTTP_PROXY=http://myproxy.mycorp.com:9999/
$ export HTTPS_PROXY=http://myproxy.mycorp.com:9998/
$ git clone https://github.com/dataversioncontrol/myrepo.git
$ cd myrepo
$ dvc pull
```
