### ISSUE TITLE
dvc add dir: file exist

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#448]
First, take a look at #447 

If a directory was already added then I got an error message:
```
$ cp -r data/SO raw  # <-- from #447
$ rm data/SO
$ dvc add raw
Unexpected error: [Errno 17] File exists: '/Users/dmitry/src/myrepo_1/.dvc/cache/ee3887acb78d695e2ac68dc85e05e2a1'
```

Is it because a directory 

Also, two minor issues:
1. Full file path.
2. Should be "Directory was already added", not "File exists".

One more related error:

```
$ rm raw/Tags.xml
$ dvc add raw

Unexpected error: [Errno 17] File exists
```

**Comment by efiop** [comment]
Not closing this one yet.
