### ISSUE TITLE
Two level cache hierarchy 

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#488]
We need to implement two-level hierarchy (`00/fcf5a6a`, `f4/3cf5a6a` etc) for DVC cache the same way as Git caches are organized.

The reason - one level slows down the operations when the number of data files (including all the versions) is very big.

**Comment by efiop** [comment]
After a bit more thinking, I agree that this also makes sense to be included in the current release. I will take a closer look soon.
