### ISSUE TITLE
dvc run: --stdout option

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#489]
We should return `--stdout` and `--stderr` options to cover cases like `head -n 1000 file.txt > file_1K.txt`:
```
dvc run -d file.txt -o file_1K.txt --stdout file_1K.txt head -n 1000 file.txt
```

**Comment by efiop** [comment]
No need, just use cover your command with ''. I.e.

dvc run -d file.txt -o file_1K.txt 'head -n 1000 file.txt > file_1K.txt'
