### ISSUE TITLE
dvc checkout performance

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#493]
Checkout works for ~24 seconds with 4K files.

This might be related to many files in one cache directory #488

**Comment by dmpetrov** [comment]
The same issue with `dvc repro` - 21 seconds with 4K files.

**Comment by efiop** [comment]
Directories are currently processed in 1 thread in checkout and repro, thus causing this kind of performance. I will look into parallelizing that soon.

**Comment by efiop** [comment]
Fixed by #532 , decreasing checkout time for 30K files from 30 seconds to 6 seconds.
