### ISSUE TITLE
comment: dvc & backwards compatibility

### ISSUE THREAD

**Issue by rdwrt** [dataversioncontrol/dvc#496]
Just a comment, I create a dvc repository in 0.8.6, perform operations, upgrade to 0.8.7. and then I get: 

"Initialization error: Not a dvc repository (checked up to mount point /)" 

If I downgrade to 0.8.6. it works  as expected again.

**Comment by dmpetrov** [comment]
@rdwrt 
Did you upgrade DVC through source code like `pip install git+git://github.com/dataversioncontrol/dvc`?

We are working on the new version 0.9 which is not compatible with the old one. The version number was still not updated. Fixed  #498.

**Comment by rdwrt** [comment]
thanks!
