### ISSUE TITLE
Full path when pushing cache files

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#519]
See the last line:
```
(18406/25001): [##############################] 100% 94/27a43c8948e41340712cd243720642
(18407/25001): [##############################] 100% 23/e84d9fe46563032c5f168c30e45749
(18408/25001): [##############################] 100% /home/ubuntu/src/dvc_tutorial/.dvc/cache/6a/c65
```

**Comment by efiop** [comment]
Are you sure you didn't use '-v' with 'dvc cache push' here?

**Comment by dmpetrov** [comment]
Yes. The last line is just flashing with full path. In general, I see only hashes in the last line, not the paths.

**Comment by efiop** [comment]
Managed to reproduce this bug and that thing you've told me about big files slowing down small ones. Investigating...
