### ISSUE TITLE
Local config is needed

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#524]
Some of the config settings are not general enough to submit into a repository but still important to keep in a local setting environment.

Examples:
1. Cloud storages can be set up locally, not globally.
2. A stage that user would like to lock. DVC files and config is probably not the best place for that.

Possible solution: store a local config `.dvc/config.local` which can overwrite (global) config settings and is ignored by Git.

**Comment by efiop** [comment]
After a bit more thinking and tinkering, I think that we should not hurry with it and leave it for consideration after the 0.9.0 release. If we do decide to implement this later, there will be no problem with backward compatibility. Closing for now.

**Comment by efiop** [comment]
This is going to be essential for #596 . Already working on it.
