### ISSUE TITLE
Investigate osx failures on travis

### ISSUE THREAD

**Issue by efiop** [dataversioncontrol/dvc#542]
https://travis-ci.org/dataversioncontrol/dvc/jobs/352413322

**Comment by efiop** [comment]
So investigation shows that mtime of files mounted in travis osx images is missing float precision, which results in our state files not being able to distinguish between files modified within 1 second. This raises a valid concern for hosts that for some reason don't have high precision timestamps.

Working on solving this right now.

**Comment by dmpetrov** [comment]
I have the same behavior on my Mac OS machine. All the timestamps with `.0` at the end. This is why I introduced a change with `int` instead of `float` which was declined.
