### ISSUE TITLE
dvc run is supper slow for directories

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#546]
It should be related to one of the recent changes since I haven't observer such issue before.

For an output directory with 25K files, it takes hours to save state. It looks like dvc saves\rewrites state file for each of the output files.

**Comment by efiop** [comment]
WIll take a look today.

**Comment by efiop** [comment]
Ah, this is a direct cause of that 'state' bug. Will be fixed with #545 . Already working on debugging that.

**Comment by efiop** [comment]
Ok, it was actually caused by us updating tinydb database way to often.
