### ISSUE TITLE
Cross branch metrics tracking

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#592]
We need to track files with metrics all across branches. As a first step let's implement a basic text file (single metrics\value in a file) and JSON. Important: metrics file can be data file as well as a regular file.

```
$ dvc metrics eval.txt
master: 0.78313
bn_03: 0.81562
bn_02: 0.81713
bn_01: 0.78829
dev: 0.68913
```

```
$ dvc metrics --json eval.json
master: {"res" { "AUC": 0.78313, "CrossValidation": 0.71245}, "something": "hello"}
bn_03: {"res" { "AUC": 0.81562, "CrossValidation": 0.741224}, "something": "hello"}
bn_02: {"res" { "AUC": 0.81713, "CrossValidation": 0.75194}, "something": "hi"}
bn_01: {"res" { "AUC": 0.78829, "CrossValidation": 0.71371}, "something": "hello"}
dev: {"res" { "AUC": 0.68913, "CrossValidation": 0.64829}, "something": "ola"}
```

Possible options:
1. `--all`, `-a` - show all branches including the branches where the metrics do not exist.
2. `--json`, `-j` - input metrics files is json.
3. `--out-json`, `-J` - output as a json.
4. `--json-path PATH` - force `--json` and output only a single metrics based on the path
5. `--fetch`, `-f` - fetch data file content if metrics file is data file and not in cache.

```
$ dvc metrics --json-path x.res.CrossValidation eval.json
master: 0.71245
bn_03: 0.81562
bn_02: 0.75194
bn_01: 0.78829
dev: 0.68913
```

**Comment by dmpetrov** [comment]
TSV file format and TSV-with-header should be covered as well.

**Comment by efiop** [comment]
Leaving '-f|--fetch' logic for the next release, there are some things to think about. Same with #656.
