### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#6]
How to work on Windows without the symlinks?

Should we use cygwin or any other unix tools for win?
How about windows10 ubuntu shell? Can we support only this version?

**Comment by efiop** [comment]
Currently, we are able to produce dvc installer for windows by running .\build.cmd from windows terminal.
The script itself(build.cmd) has sufficient explanation about requirements and has info on where to get them.

When releasing new version of dvc, windows installer should be built and binary should be included into release as described here: https://help.github.com/articles/creating-releases/ .

Here is a test installer for dvc-0.8.4 to try it out: https://drive.google.com/file/d/0BxlwKSeztewYM0t6ckdIUm1ESFE/view?usp=sharing .

About symlinks: currently we are able to work with symlinks by adding CreateSymLink privilege to users(separate checkbox in the installer), but it would be nice if we could also work without symlinks(if at all possible).

Not closing this issue for now.

**Comment by efiop** [comment]
Added feature request for symlink-less dvc.
Verified that windows installer works for other people too, thus closing this issue now.
