### ISSUE TITLE
DVC data tracking

### ISSUE THREAD

**Issue by rahulguptajss** [dataversioncontrol/dvc#602]
Hi,

I have a query for below sample dvc run command.

dvc run -d data/CombinedSummary.csv -d source/scripts/split_train_test.py -o data/train.p python source/scripts/split_train_test.py

1: Above command doesn't track any changes data/CombinedSummary.csv. For this, I need to explicitly mention dvc add data/CombinedSummary.csv. Is it expected feature or i am missing something. Ideally, my input data should be automatically fall under dvc.

2: -d source/scripts/split_train_test.py does track changes in my py file. If i change anything in py file and run dvc repro then my ML pipeline works as expected. A bit confused between -d command for file input and py file.

**Comment by efiop** [comment]
Hi @rahulguptajss !

When you specify -d FILE, dvc calculates md5 of that file and saves the inode. Then, if the contents(or inode) of the FILE changes, dvc detects it and tries to reproduce the stage. So both csv and py files are actually tracked the _same_ way in this case. The only difference between running 'dvc add .csv' and not running it is in that your csv file will not be cached by dvc, so you will not be able to 'dvc pull/push' it. Could you please provide the contents of that dvc file? I.e. `cat train.p.dvc`. 

Also, lets try and see if the minimal example works for you. Could you please run the following commands and show the output?
```
echo old > test_file
dvc run -d test_file -o copy cp test_file copy
cat copy.dvc
echo new > test_file
dvc repro copy.dvc
cat copy.dvc
```

**Comment by rahulguptajss** [comment]
Thanks its a lot clearer now. I was a bit confused with dvc track and add. I was thinking that add is a must for tracking in dvc. Below is the cat of this file and it clearly is tracking inputs and outputs. It's working correctly now.

cmd: python source/scripts/split_train_test.py
deps:
- md5: 5fb9105c342df2de330913ae8e3767a7
  path: data\CombinedSummary.csv
- md5: 688eeb0836d7034cf1cfd53c1333ff5f
  path: source\scripts\split_train_test.py
outs:
- cache: true
  md5: 184b9aee2f5df48f1ed2cf22d3c33d07
  path: data\train.p

**Comment by efiop** [comment]
I'm glad it helped :) If the issue is solved, feel free to close it.

**Comment by rahulguptajss** [comment]
Sure thank you :)
