### ISSUE TITLE
DVC data size query

### ISSUE THREAD

**Issue by rahulguptajss** [dataversioncontrol/dvc#603]
Hi,

I have a query from data size perspective. If my input data is 100 GB. Considering dvc creates multiple version of this input data based on the modification, does it mean that i do need a very huge local disk space? Do we have any archive feature in dvc. 
I am trying to integrate my pipeline with jenkins where I probably will be running dvc repro a lot.

**Comment by efiop** [comment]
Hi @rahulguptajss !

If you need all the previous versions of that file then yes, you will have to provide the huge amounts of storage. But if you don't need older versions, you could simply run `dvc gc` that will remove all the old unused versions and will only leave the currently used ones.

**Comment by rahulguptajss** [comment]
Thanks this will help. I can keep older versions in cloud.
