### ISSUE TITLE
Use URLs instead of multi-part specifications for remotes(clouds)

### ISSUE THREAD

**Issue by efiop** [dataversioncontrol/dvc#606]
We are now using such notation for our clouds:
```
[AWS]
StoragePath = dvc/tutorial
Region = us-east-2
...
[GCP]
StoragePath = dvc/tutorial
ProjectName = dvc-proj
```
But many of the parameters can be easily retrieved from the default config files(e.g. ~/.aws or ~/.gsutil) or detected automatically(e.g. s3 region). What we should do instead is:
```
[remote "my-s3-cloud"]
url = s3://dvc/tutorial
< Possible additional parameters >
[remote "my-gcp-cloud"]
url = gs://dvc/tutorial
< Possible additional parameters >
```
Doing it this way fits nicely within the #596  and looks much better then [AWS] and [GCP] sections.

**Comment by dmpetrov** [comment]
Do we need to create a special file or a directory for remote settings like Git has?

**Comment by efiop** [comment]
@dmpetrov Git stores everything in .git/config and so will we. Already working on fixing up our config to accommodate that nicely.

**Comment by dmpetrov** [comment]
Oh. Right. Git uses `remote` directory for branch tracking like `.git/refs/remotes/origin/bugfix11`, not for actual remotes.

**Comment by efiop** [comment]
Yeah, our remotes are much simpler than git's(i.e. we don't even have refs or anything similar to that), so looks like storing remotes list in config is all we are going to need.
