### ISSUE TITLE
Support for file server or hdfs

### ISSUE THREAD

**Issue by rahulguptajss** [dataversioncontrol/dvc#637]
Hi,

Do we have support for FTP/HDFS for dvc push/pull. If not, are there any plans to support this in near future?

**Comment by efiop** [comment]
Hi @rahulguptajss !

In 0.9.5 we support aws, gcp and local storage only. In 0.9.6 we will also support ssh. As to hdfs, we have received a number of requests and will look into supporting it in the nearest future as well.

**Comment by efiop** [comment]
Sure. So the local storage is simply storing your cache in another directory. Example:
```
dvc config Core.Cloud LOCAL
dvc config LOCAL.StoragePath /tmp/mycloud
dvc push
```
As simple as that.

**Comment by rahulguptajss** [comment]
awesome thanks a lot. :)
