### ISSUE TITLE
Extracting DAG out of dvc and run it in Tez

### ISSUE THREAD

**Issue by rahulguptajss** [dataversioncontrol/dvc#645]
Is it possible to extract DAG out of dvc pipeline and run it on Tez. 

https://tez.apache.org/

**Comment by efiop** [comment]
I am not very familiar with tez, but it definitely seems possible. All one would need is to parse DAG of the dvc project(which is fairly easily done by parsing individual .dvc files and following dependencies) and put it into tez format.
