### ISSUE TITLE
Conditional Statement Support for dvc pipeline

### ISSUE THREAD

**Issue by rahulguptajss** [dataversioncontrol/dvc#646]
Can we define a DAG in dvc such that it supports conditional statements on input/output of a pipeline step?

**Comment by efiop** [comment]
No, currently you can't. However, we do plan on providing a support for cmd-dependencies. I.e. -something like `dvc run --cmd-dep condition.py -d input -o output cmd input output`, where condition.py is your script that dvc will run to determine if stage has changed. This way you could process any kinds of conditions in your script. I've added a task for it: #648

**Comment by bjornarmr** [comment]
I would like this feature at some point. 

- If isAccuracyImproved
    do some tasks -> like put to staging environment.
- else: 
    do some other tasks
