### ISSUE TITLE
DVC automated pull and push

### ISSUE THREAD

**Issue by rahulguptajss** [dataversioncontrol/dvc#657]
Hi,

Is it possible to configure dvc  pull/push to run automatically with git pull/push? Considering these operations work hand in hand and will always be required. Manually calling dvc push/pull could lead to sometimes mistakes and data inconsistency.

**Comment by villasv** [comment]
Seems pretty easy to achieve with git-hooks. I don't see why this would cause inconsistency. At worst, you would recalculate unnecessary stuff (assuming the pipeline is deterministic, nothing would go wrong).

Perhaps dvc could come with some standard git-hook instalation command, like `nbstripout install` does.

**Comment by rahulguptajss** [comment]
Thanks. This would be a good feature built into dvc. I will look into git hooks as well.
