### ISSUE TITLE
dvc repro with --confirm option

### ISSUE THREAD

**Issue by prihoda** [dataversioncontrol/dvc#667]
Hi, could we have a `dvc repro --confirm` mode that asks before reproducing each dependency? Or a `dvc repro --preview` mode that just shows the reproduction plan? 

When there are changes back in the dependency chain that I didn't expect and the reproduction starts from the beginning, I want to be able to cancel the reproduction without getting the dependent data files removed. 

I know this can be solved in the basic case by running in `--single` mode, but what if I want a `--double` mode that also includes the parent dependencies and so on? 😄

**Comment by efiop** [comment]
Hi @prihoda !

Great suggestion! Maybe something like `dvc repro --iterative`?

Btw, you can also use `dvc status`(it is still a bit raw, but none the less) to see what has changed in your pipeline, so that there are no 'unexpected reproductions' :D

**Comment by efiop** [comment]
hi @prihoda !

Have you tried `dvc status` ? Does it solve your issue?

**Comment by prihoda** [comment]
Yes, this should be enough 👍 I'm usually using `dvc repro -s` anyway in case I only want to reproduce that single file.

**Comment by efiop** [comment]
Glad `dvc status` solved it for you. Closing this issue for now. Feel free to reopen.
