### ISSUE TITLE
Update and propagate md5 hash of existing file

### ISSUE THREAD

**Issue by prihoda** [dataversioncontrol/dvc#668]
Example: When I change a file in a way that doesn't affect processing of the dependent files (e.g. adding a comment to a script file, adding an extra column to a CSV file). I want to tell DVC that the file content (=md5 hash) changed but that I don't want to process the dependent files again.

I think there are two options:

- Running a command on the changed file:
    - For data files, this could be done by running `dvc add` again. Currently, when you run `dvc add file.csv` on a data file, the existing `file.csv.dvc` is overwritten. Instead, you could overwrite just the output md5 field.
    - The md5 change would propagate into directly dependent `.dvc` files. 
    - However, we don't want to run `dvc add` on non-data files (e.g. scripts). Maybe this would have be a whole new command like `dvc propagate file.csv`?
- Running a command on the dependent `.dvc` files: 
    - Update the `.dvc` md5 fields based on the current deps and outs file content. This is basically the reverse of `dvc repro`, maybe it could be added as an argument like `dvc repro --refresh`?
    - Probably easier to implement, but harder to use since the user would have to run on all dependencies separately (but again, maybe that's desirable?)

Do you think that would be useful?

Thanks! I'm excited about this tool very much! 👏

**Comment by dmpetrov** [comment]
Thank you @prihoda! It looks like a useful and very practical feature. I feel it like `git squash` - hack by nature but sometimes it is very useful. I don't think we can avoid this kind of hacks in real life.

A couple more open questions:
1. Should DVC write additional information about this trick? Something like `propagated: true`.
2. Adding a comment to a script file is a good scenario. But editing data file is questionable. For data sources - why don't we just remove and add a new data file? For data derivatives - we probably should not support this feature since it breaks reproducibility chain. So, should DVC support that for data files at all?

**Comment by prihoda** [comment]
About no. 2: As you said, it's a bit of a hack, the user would have to know about the impact. I think it's useful even for data files, in case they are really expensive to reproduce, you changed their dependencies, but the change can be applied by hand instead. 

E.g. I realized I want a different column name in a CSV file -> change the script that generates the file, apply the change to the file by hand, run `dvc propagate`.

**Comment by prihoda** [comment]
This would also be useful when using DVC for an existing project. Currently there is no way to create valid .dvc files (with dependencies and build command) from existing files without reproducing them.

**Comment by efiop** [comment]
Hi @prihoda !

Thank you for your feedback! These are indeed some very interesting ideas. 

> This would also be useful when using DVC for an existing project. Currently there is no way to create valid .dvc files (with dependencies and build command) from existing files without reproducing them.

There is actually a way to do that right now. If you really need that kind of hack, you can simply write dvc files by yourself, without `dvc run`. Dvcfiles have very simple yaml format, so there should be absolutely no problem to write it by-hand. I.e. lets say I have my script.py, input.data and output.data files that are already there. Now I can hack my way in by simply creating script.dvc and calculating md5 of imput.data, output.data and script.py with md5sum utility myself and pasting the checksums into the script.dvc's deps and outs(just look at any existing dvc file to get the idea where to put what).

What worries me the most about `dvc propagate` is just how easy it is to shoot yourself in the leg, if you mess up in any of the steps and break the reproducibility only to realize that your project is broken some time later when you actually need to reproduce it. Thus I don't think that we should encourage that kind of behavior, instead we should simply suggest rebuilding your pipeline with dvc. Yes, it will take some time to rebuild the pipeline, but at least you will be 100% sure that your project actually works, which is the most important thing in my opinion. That being said, I do realize that there are use cases for `dvc propagate`, but I'm not yet convinced that we should actually embrace it and include such feature into core dvc. Lets leave this issue open for now, we will discuss it more carefully soon and come back to it.

**Comment by prihoda** [comment]
Great to know! I am editing .dvc files but didn't realize I can generate the hashes so easily. 

After using DVC for a while I see that the `dvc propagate` command would violate the guarantees you want to create in the first place. I guess this would only make sense as an extension for the `dvc add` command - to be able to specify dependencies (and also the build command if possible).
