### ISSUE TITLE
Pull request on Ubuntu fails

### ISSUE THREAD

**Issue by zacharymostowsky** [dataversioncontrol/dvc#689]
Hello,

I am using dvc to share large files among developers as an add on to git. I have yet ot have the need for the reproducibility of ML pipelines. Everything works fine on windows and I can push and pull files to the cloud from different machines. In the case of my Ubuntu 16.04 vm I run into the following issue after cloning the repository and trying a dvc pull / checkout. I have installed dvc through pip install on my Ubuntu machine and the executable on my windows machine.

First, if I try the pull right after git clone ([As specified in this blog post](https://blog.dataversioncontrol.com/data-version-control-tutorial-9146715eda46)), I get the following error:

Using obsoleted config format. Consider updating.
Using obsoleted config format. Consider updating.
Using obsoleted config format. Consider updating.
File '/home/myhomedir/Desktop/my-project/.dvc/cache/f1/7e665784e54636457018742e41659f' does not exist in the cloud
'.dvc/cache/f1/7e665784e54636457018742e41659f(myfolder/test_4_0.jpg)': cache file not found

I have tried googling around and checking issues here but no luck.

Then, if I try a git clone and then dvc checkout ([as specified in the updated help docs](https://github.com/dataversioncontrol/dvc/blob/master/docs/doc.rst)) I get a similar issue, except dvc cannot find a file in the cache this time. I assume this is because dvc hasn't executed the pull from the cloud. Error:

Using obsoleted config format. Consider updating.
'.dvc/cache/f1/7e665784e54636457018742e41659f(DIUX Object Detection Engine/test_4_0.jpg)': cache file not found

Again, I can execute these commands fine on Windows.

Thank you in advance for your help. I love this solution, just need it to work cross platform.

Zach

**Comment by zacharymostowsky** [comment]
Hi  @efiop ,

This is almost certainly the issue. I have just confirmed I am running version 0.9.0. I will upgrade, perform the necessary fixes  and report back. I appreciate your timely reply. Also, may want to update https://dataversioncontrol.com/ so the download reflects the newest version!

Thanks,
Zach

**Comment by efiop** [comment]
@zacharymostowsky Good catch! We will update that ASAP, thank you!

**Comment by zacharymostowsky** [comment]
Hi @efiop , I can confirm that this has solved my issue. Thank you for your help.

Zach

**Comment by efiop** [comment]
Hi @zacharymostowsky !

I'm glad it helped! Thank you for the feedback!
