### ISSUE TITLE
Graph construction during DVC repro --single-item

### ISSUE THREAD

**Issue by prihoda** [dataversioncontrol/dvc#710]
With large project graphs, the `dvc repro --single-item file.dvc` command spends a very long time (minutes) on constructing the graph before running the command. 

Do we need to construct the whole graph in single mode?

**Comment by efiop** [comment]
Hi @prihoda !

Indeed, there seems to be no need in constructiong graph before running this command. Though, the delay is mostly caused by the inefficiency of graph construction and related to #711 . I will look into solving this today.

Thanks,
Ruslan
