### ISSUE TITLE
Wrapper shell that removed need to type "dvc run --shell" before every command?

### ISSUE THREAD

**Issue by talwrii** [dataversioncontrol/dvc#72]
I haven't used dvc enough to know whether this is a good idea.

It should be noted that this is pretty trivial with zsh by overriding the accept-line functions:

Untested: 
```
dvc-accept-line () {
    if [[ ! "$BUFFER" =~ "dvc " ]]; then
        BUFFER = "dvc run --shell \"$BUFFER\"" # This does not deal with quoting correctly - should do something with prrintf here
    fi;
    .accept-line
}
zle -N dvc-accept-line

zle -A dvc-accept-line accept-line
```

**Comment by efiop** [comment]
Hi @talwrii !

Thank you for your feedback!

I definitely see how --shell might be a bit frustrating as it wastes keystrokes in cases when you use 'dvc run' to run a lot of small hand-written commands. But in a more real scenarios you would probably use bigger commands and reuse the ones from your shell's history and at this point the inconvenience of additional keystrokes for --shell becomes negligible. Also, using --shell on windows vs *nix has important differences and I don't think we should hide it under the wrappers as it will probably introduce more confusion than convenience. Just imagine running the same command on windows and linux through the corresponding wrappers and getting different results. This is especially important as we rely on specified command when running 'dvc reproduce'.

I would refer to 'docker exec' as an example of similar command, where --shell is not available at all and users are forced to use something like bash -c "COMMAND" to workaround it. I think we should do the same and leave --shell for implicit usage.

Closing this issue for now.
