### ISSUE TITLE
"updater is not old enough to check for updates"

### ISSUE THREAD

**Issue by mfrata** [dataversioncontrol/dvc#725]
Guys i've tried to use `dvc push` and received this answer back. What this means?

**Comment by efiop** [comment]
You probably passed `-v` to it. This means that dvc is not ready to check for dvc updates, totally unrelated to the function of `dvc push`. Just ignore it.

**Comment by mfrata** [comment]
Yeah. But if a haven't set the access of the cloud, shouldn't this guy raise an error?

**Comment by efiop** [comment]
You are right, it should at least print a warning that there is no remote setup. Thank you for noticing! Created https://github.com/dataversioncontrol/dvc/issues/726 for that. Feel free to close this issue if it resolved.

**Comment by mfrata** [comment]
Thank you for the quick response, i have other doubts about the dvc but i will open more issues
