### ISSUE TITLE
Global Cloud configuration is failed

### ISSUE THREAD

**Issue by e-mon** [dataversioncontrol/dvc#728]
following error is occurred.

```
$ dvc --version
dvc 0.9.7
$ dvc config Global.Cloud GCP
$ dvc status
Initialization error: Config file error: Wrong keys 'global' in {'global': {'cloud': 'GCP'}}
```

.dvc/config
```
[Global]

Cloud = GCP
```

**Comment by efiop** [comment]
Hi @e-mon !

This syntax was obsoleted a while ago and no longer supported. We are currently working on updating the docs. Please try a modern approach:
```
dvc remote add myremote gs://mybucket/path
dvc config core.remote myremote
```
These two commands should be enough. Please let us know if it worked for you.

Thanks,
Ruslan

**Comment by e-mon** [comment]
its' solved!
thank you for your answer !

**Comment by analystanand** [comment]
working fine. please consider updating docs. 
Thank you.
