### ISSUE TITLE
dvc init errors "<dir> is not tracked by any supported scm tool" inside initialized git repository

### ISSUE THREAD

**Issue by villasv** [dataversioncontrol/dvc#729]
Probably this is a bug in the python git lib, but reporting here anyway.
I'm using the WSL bash to work on my project, but running `dvc init` yields:

```
➜  src git:(master) ✗ dvc init
Failed to initiate dvc: /mnt/c/Users/villasv/Projects/sigir-multitarget-retrieval/src is not tracked by any supported scm tool(e.g. git).
```

Running `dvc init` using PowerShell works fine. Subsequent commands like `dvc run` works fine, as IIRC they don't depend as much in git.

**Comment by villasv** [comment]
But I did have `git init`ed the repository, of course. You can see it in my bash line showing the current branch. And like I said, running `dvc init` on PowerShell right afterwards worked fine.

**Comment by efiop** [comment]
Sorry, didn't notice that right away. 

Hm... We actually use pretty simple way of detecting whether or not it is a gid dir, by just checking if .git exists. So this error is pretty strange. Are you using cygwin?

**Comment by efiop** [comment]
Ah, wait a second. Is 'src' a subdir of your repository? If so, you should call `dvc init` in the project's root, which is probably what you did from a PowerShell.

**Comment by villasv** [comment]
Aww, sorry. When I tried to reproduce it with PowerShell I should've made sure the conditions were exactly the same. Yeah, I didn't run `dvc init` in the repository root directory.

Thanks :) I'll rename and close.

**Comment by daniyalkhan131** [comment]
thanks, I was also doing the same mistake
