### ISSUE TITLE
Save stdout as output file using DVC run --log 

### ISSUE THREAD

**Issue by prihoda** [dataversioncontrol/dvc#733]
Hey guys. In my workflow I often want to save the standard output to a log file. This is possible using:
```
dvc run -o plot.png -o plot.log './create_plot.py plot.png | tee plot.log'
```

Which is already quite ok 👍But I was wondering how difficult would it be to integrate it directly to `dvc run`, for example as `dvc run --log` to automatically add this log file to the list of outputs and redirect stdout to it. It might even be a configurable setting to create these log files with each `dvc run`.

I guess you cannot just automatically add '| tee file.txt' to the cmd field since there might be multiple commands. There would have to be some extra logic.

**Comment by efiop** [comment]
Hi @prihoda !

We actually had --stdout argument in an old(pre-redesigned) version of dvc, but it was proved to be cumbersome, that is why we decided to remove it in favor of what seems to be a more natural approach of using pipes or just directly modifying your code to store logs somewhere. Plus, it raises a question of whether or not the log should be tracked by dvc or not, thus producing multiple unnecessary options(i.e. --stdout, --stdout-no-cache, --stderr, --stderr-no-cache) which make the things even more complicated for both us and users, as `-o log.log './mycmd.py &> log.log'` (or `-o log.log ./mycmd.py` if you modify your own script) is much easier to read than `--stdout log.log --stderr log.log ./mycmd.py`. Thus I don't think that `--log` or equivalent is necessary, at least as of right now.

Thanks,
Ruslan

**Comment by villasv** [comment]
I'm against that feature request. If your step produces output, it's best to redirect it yourself. It's so much more flexible, because you could grep\sed\awk stuff in any way you want and DVC should handle it naturally.

**Comment by prihoda** [comment]
Good points! Closing this issue.
