### ISSUE TITLE
Symlink-less DVC for Windows

### ISSUE THREAD

**Issue by efiop** [dataversioncontrol/dvc#77]
Currently we are able to work with symlinks by adding CreateSymLink privilege to users(separate checkbox in the installer), but it would be nice if we could also work without symlinks(if at all possible).

**Comment by dmpetrov** [comment]
Yeah. It would be nice. But I'm not sure it is possible. I'd appreciate any ideas.

**Comment by efiop** [comment]
Closed with #275 .
