### ISSUE TITLE
Currently affected by a pip bug

### ISSUE THREAD

**Issue by villasv** [dataversioncontrol/dvc#82]
DVC package is currently affected by this bug https://github.com/pypa/pip/issues/4216

Since `pip` is currently the only official way to install, it might be better to solve it locally instead of waiting for that bugfix.

**Comment by efiop** [comment]
@villasv Could you share more details about the issue you are experiencing? From what I can gather from the link you've provided, is that you are not able to install dvc using pip in your virtual env. Right? I would really appreciate more details.

**Comment by villasv** [comment]
System: Windows 10 (Preview Build 16199)
Python: 3.6
Pip: 9.0.1 and 10.0.0.dev0

No virtualenv.

Currently tested only in one machine, reproducing with:
`pip install dvc`
...
`AttributeError: '_NamespacePath' object has no attribute 'sort'`

**Comment by villasv** [comment]
Just reproduced in a linux environment (Fedora 25):

- pip 9.0.1 (python 3.5) from conda
- pip 9.0.1 (python 3.5)

Using pip 8 from python 2.7 works fine.

**Comment by dmpetrov** [comment]
@villasv thank you for reporting this! We are working on DVC window package (not released yet). It can help you in mitigating the issue. 

@efiop could you please verify if the windows package have this issue?

**Comment by dmpetrov** [comment]
@villasv DVC Windows installer is available here:
https://s3-us-west-2.amazonaws.com/dvc-share/dist/dvc-0.8.4.exe

This DVC package does not depend on your local Python and has no issues with pip.

And, yes, we will close the issue since it is pip-issue, not DVC.

**Comment by dmpetrov** [comment]
This is pip-issue and could be solved by upgrading setuptools or by Windows installer.
