### ISSUE TITLE
MAC OS X (Brew) installer

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#86]

**Comment by efiop** [comment]
https://github.com/dataversioncontrol/dvc/pull/88 introduced needed PyInstall hooks for dvc, so it should be as easy as copying build_linux.sh to build_osx.sh and using "fpm_build osxpkg" instead of "fpm_build deb". Still need to actually try it on Mac, there might be some surprises.

**Comment by efiop** [comment]
We discussed this with @dmpetrov  and decided to ignore this issue temporarily as we already have mac installer as a standalone pkg. Removing from recent milestone.

**Comment by dmpetrov** [comment]
@efiop what do you think now about the `Brew` installer? Has your opinion changed?

**Comment by efiop** [comment]
@dmpetrov It just wasn't necessary for that milestone, but in general I think that we definitely need one. I'll revisit this soon.

**Comment by efiop** [comment]
We now have our own brew tap at https://github.com/dataversioncontrol/homebrew-dvc, which, for now, only has cask script.

**Comment by efiop** [comment]
Also added a regular formula.
