### ISSUE TITLE
feature request: consider using a single commit when importing a directory of files

### ISSUE THREAD

**Issue by ophiry** [dataversioncontrol/dvc#91]
I believe that when importing a set of file, the common case is to treat them as a single logical unit of data.
having a single commit will allow rolling back or switching versions in a more natural way

**Comment by efiop** [comment]
Hi @ophiry ! We actually introduced this behavior just a day ago in https://github.com/dataversioncontrol/dvc/pull/90 . Please feel free to try it out!

**Comment by efiop** [comment]
Closing this issue as the feature was introduced in #90 . Feel free to re-open if needed.
