### ISSUE TITLE
Error when syncing data subfolders in new repos

### ISSUE THREAD

**Issue by adaptorel** [dataversioncontrol/dvc#94]
Importing data into a data/ subfolder works as expected after creating that subfolder, *dvc import data/subf/big_file.msg* Synching also sends it to S3 into the appropriate folder structure. However when syncing into new projects/clones (dvc sync data/) and most probably existing ones it'll cause this error:

```bash Downloading cache file from S3 "bucket/project/.cache/subf/big_file.msg"
Error. Cannot sync file data/subf/big_file.msg: [Errno 2] No such file or directory: '.cache/subf/big_file.msg'
```

And then if you go and create the *.cache/subf* folder manually and *dvc sync data/* again all is well and data scientists are happy. But dvc creating that folder would make them even happier and more productive ;-)

virtualenv/Python 2.7, MacOSX Sierra, dvc (0.8.4)

**Comment by dmpetrov** [comment]
@adaptorel thank you for reporting! It will be fixed soon.
