### ISSUE TITLE
Progress bar for sync cmd

### ISSUE THREAD

**Issue by dmpetrov** [dataversioncontrol/dvc#96]
Please use import command as an example.

Note: It would be great to increase unit test coverage for progress class.

**Comment by dmpetrov** [comment]
@efiop Would you be able to take this issue?

**Comment by efiop** [comment]
>> Please use import command as an example.

@dmpetrov What do you mean by that?

**Comment by efiop** [comment]
Oh, right, progress bar for data sync. Understood. Sure, I was going to do it too

**Comment by dmpetrov** [comment]
Awesome!
